name: Deploy ARM Template

on:
  push:
    branches:
      - main
env:
  AZURE_SUBSCRIPTION_ID: e4c51041-6982-4771-ad5e-fcea810fe303   # set this to your Azure Subscription Id
  AZURE_RESOURCE_GROUP: mynewdevopsvm   # set this to your target resource group

jobs:
  deploy-virtual-network-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # changed 

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          region: eastus
          template: newaksdeploy.json
          parameters: newaksdeploy.parameters.json
